
platiglib_project: rbpse

dataset:
  name: RBPSEDataset
  three_exon_combos: all
  cell_line: HepG2
  window: 100
  min_read_count: 40

  features: 
    binding_matrix: 
      binding_format: 'binary'
      in_silico_kd: true

  rebalance: 
    method: binned_downsampling
    num_bins: 2
    seed: 17

training:

  data_split: 
    method: random_set_defs
    train_size: 0.7
    validate_size: 0.1
    test_size: 0.2
    group_column: ensembl_gene_id

  wandb:
    track: true
    project: yogi-downsampling-october-2025

  seed: 17

model:
  name: XGBRegressor

  # CONSTANT BASE HYPERPARAMETERS
  n_jobs: -1
  eval_metric: ['rmse', 'logloss']
  n_estimators: 100000

  early_stopping_rounds: 100  
  max_depth: 3
  learning_rate: 0.05

  # FIXING OTHER HYPERPARMETERS
  min_child_weight: 30
  gamma: 0.5
  subsample: 1
  colsample_bytree: 0.75
  reg_lambda: 5
  reg_alpha: 0