dataset: 
        cell_line: 
            [K562, HepG2]

        distance: 
            [50, 100, 150, 200, 250, 500]

        control_only: 
            [False, True]

        psi_subset: 
            [null, [0, 1], [0.1, 0.9]]

        read_count_quantile: 
            [null, 0.1, 0.2, 0.4,]

        data_flavor: 
            [binary, num_peaks, rbp_exp, rbp_exp_peak]

        count_normalization_method: 
            [getmm, tmm]

        log_counts: 
            [False, True]


modeling:
        model: [OLSRegression, ElasticNetContinuous, OLSOrdinalRegression, ElasticNetOrdinal, OrdinalGBT]
        random_state: [17, 97]
        data_splitting_method: "gene"
        train_split: 0.7
        test_split: 0.15
        validate_split: 0.15