# Sweep configuration
sweep:
  name: 2:min_child_weight-gamma:K562
  project: yogi-rbp-ml-gencode-v24-v29-matching-exons

  method: grid
  metric:
    name: holdout_r2_score
    goal: maximize

# Base configuration
config_overlay:

  platiglib_project: rbpse

  dataset:
    name: RBPSEDataset
    data_source: 
      EncodeRBPBindingDataSource:
        cell_line: K562
        three_exon_combos: all
        min_read_count: 40
        window: 100

    features: 
      binding_matrix: 
        binding_format: 'binary'
        in_silico_kd: true

    fold_filter:
      num_folds: 5
      fold_index: 1
      group_column: ensembl_gene_id
      side: train
      seed: 17
  
  training:

    data_split:
      method: cross_validation
      num_folds: 5
      group_column: 'ensembl_gene_id'
      validate_frac_of_train: 0.10
  
  model:
    name: XGBRegressor

    # CONSTANT BASE HYPERPARAMETERS
    n_jobs: -1
    eval_metric: ['rmse', 'logloss']
    n_estimators: 100000
    early_stopping_rounds: 100

    # FROM PREVIOUS SWEEP
    learning_rate: 0.01
    max_depth: 5

    # FIXING OTHER HYPERPARMETERS
    subsample: 1
    colsample_bytree: 1
    reg_lambda: 1
    reg_alpha: 0


# Parameters to sweep
parameters:

  # INCLUDED IN ALL SWEEPS
  training.seed: 
    values: [100, 200, 300, 400, 500, 600, 700]

  # TREE SPLITTING PARAMETERS
  model.min_child_weight:
    values: [1, 5, 10, 50, 100]
  model.gamma:
    values: [0, 0.5, 1, 2, 5]